server_host="0.0.0.0:9191"
env = "prod"
dist_dir = "dist"
ssr_timeout = 15
content_security_policy = "form-action 'self'; frame-ancestors 'self';"
alarm_url = ""
alarm_secret = ""

[Log]
debug=false
filenum=20
filesize=256
filename="run"
level="INFO"
dir="/data/vue-ssr-v8go/log"

[V8vm]
use_strict = true
delete_delay_time = 10
heap_size_limit = 1408
instance_lifetime = 3600
max_instances = 10
xmlhttprequest_threads = 50

[Api]
location_origin = "https://test.com"
hosts = ["test.com"]
targets = ["http://127.0.0.1:5500"]
