server_host="0.0.0.0:9191"
env = "prod"
alarm_url = ""
alarm_secret = ""

[Log]
debug=false
filenum=20
filesize=256
filename="run"
level="INFO"
dir="/data/vue-ssr-v8go/log"

[V8vm]
use_strict = true
delete_delay_time = 10
heap_size_limit = 1408
instance_lifetime = 3600
max_instances = 10
xmlhttprequest_threads = 50

[SSR]
dist_dir = "dist"
timeout = 15
response_headers = ["Content-Security-Policy: form-action 'self'; frame-ancestors 'self';"]
origin = "https://test.com"
origin_rewrite = "http://127.0.0.1:5500"
